name: "Build and Publish to PyPI"
on:
  workflow_dispatch:
  push:
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    environment:
      name: testpypi
      url: https://test.pypi.org/legacy/
    permissions:
      id-token: write
    steps:
    - name: set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: install
      run: pip install -U build
    - name: build
      run: python -m build --sdist --wheel --outdir dist/

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
