name: TestAPI

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [3.10]
        #include:
          #- os: ubuntu-latest
            #python-version: 3.10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install python dependencies
      shell: bash -l {0}
      run: |
        pip install helics
        pip install pydantic
    - name: Install python package
      shell: bash -l {0}
      run: |
        cd API
        python setup.py develop
    - name: Run integration tests
      shell: bash -l {0}
      run: |
        bash API/test/runtests.sh
    - name: Archive test logs
      uses: actions/upload-artifact@v2
      with:
        name: testlogs
        path: |
          API/test/test_basic_system/*.log
          API/test/test_mock_system/*.log
