name: UnitTests

on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install pytest
      shell: bash -l {0}
      run: |
        pip install pytest
    - name: Install python package
      shell: bash -l {0}
      run: |
        python setup.py develop
    - name: Run unit tests
      shell: bash -l {0}
      run: |
        pytest tests/unit_tests/
